### PR TITLE
Milestone: feature add greeting app front-end

### PR DESCRIPTION
**Pull request by musangamfure**
## Change in this pull request

In this pull request I:

- Created a new React app

- Initialized the project with Git.

- Created the App component with react-router.

- Created the Greeting component that will display a greeting. Set it up as a route in your App component.

- Created a store, an action, and a reducer that will connect to the API endpoint to get the random greeting.

- Display the random greeting in your Greeting component.

### CODE REVIEW

**Comment by addod19** [comment]
## Hi @musangamfure, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that is invalid because the link to the backend PR is broken and also some relevant headers are missing; like key features, etc. Here is a link to the [README template](https://github.com/microverseinc/readme-template)

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by addod19** [comment]
## Hi @musangamfure, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that is invalid because README lacks relevant headers. Kindly compare and add all the relevant headers like the future features. In the earlier review, there was a link to the [README template](https://github.com/microverseinc/readme-template) we can compare ours with. It's only the FAQ that is optional

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by brainconnect93 — CHANGES_REQUESTED** [review]
### Hi @musangamfure , 👋 

# STATUS: Changes Required :recycle:

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!



## Good Points 👍

- Descriptive Pull Request title & summary. ✔️
- "Hello world" project with `react-rails` gem ✔️
- Implement the `API` in the backend correctly ✔️
- Add link to the `Frontend` in the README file ✔️ 
- Good use of Git flow ✔️

### Changes Required

- [ ] Great effort working on your project, but when I try to check the random greetings by navigating to the API URL it throws an error and after checking through your code I realize you haven't defined a method index in your greetings_controller. Instead of `def random`, it should be `def index`
- Also I realized I could not get the random greetings displaying on the browser in the front-end application. 

Below is a video recording for my claim 👇

[screen-capture (3).webm](https://github.com/musangamfure/hello-rails-back-end/assets/78634841/b0b4fec9-1e61-400f-8459-012b1b9b971c)


- [x]  _Please check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me on( @brainconnect93 ) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by rloterh — APPROVED** [review]
## Status: Approved :heavy_check_mark:

Hi Emmanuel,  

 **Set up a 'Hello world' project with two apps** task is complete! 🏁 Congratulations!  🎉💯🌟 

## Highlights 🎯 
🎲 Backend API correctly connects with Reat frontend externally!
🎲 Random greeting are generating correctly!

Cheers..Happy coding!..and keep soaring higher! 💻 🍷 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
